export const LOGGED_IN_USER_DATA = "LOGGED_IN_USER_DATA";
export const SET_LOGGED_IN_USER_DETAILS = "SET_LOGGED_IN_USER_DETAILS";
export const CHANGE_USER_PERMISSION = "CHANGE_USER_PERMISSION";
export const SET_IS_LOGGEDIN = "SET_IS_LOGGEDIN";
export const SET_IS_LOGGEDOUT = "SET_IS_LOGGEDOUT";
export const SET_SELECT_MEMBER_INFO = "SET_SELECT_MEMBER_INFO";
