export const SET_MASTER_DATA = "SET_MASTER_DATA"
export const GET_MASTERS_DATA_REQUEST = "GET_MASTERS_DATA_REQUEST"
export const GET_MASTERS_DATA_REQUEST_SUCCESS = "GET_MASTERS_DATA_REQUEST_SUCCESS"
export const GET_MASTERS_DATA_REQUEST_ERROR = "GET_MASTERS_DATA_REQUEST_ERROR"
export const SET_SITE_DATA = "SET_SITE_DATA"


export const SET_LOCATION_TYPE_MASTER_DATA = "SET_LOCATION_TYPE_MASTER_DATA"
export const GET_LOCATION_TYPE_MASTER_DATA_REQUEST = "GET_LOCATION_TYPE_MASTER_DATA_REQUEST"
export const GET_LOCATION_TYPE_MASTER_DATA_REQUEST_SUCCESS = "GET_LOCATION_TYPE_MASTER_DATA_REQUEST_SUCCESS"

export const SET_STATUS_MASTER_DATA = "SET_STATUS_MASTER_DATA"
export const GET_STATUS_MASTER_DATA_REQUEST = "GET_STATUS_MASTER_DATA_REQUEST"
export const GET_STATUS_MASTER_DATA_REQUEST_SUCCESS = "GET_LOCATION_TYPE_MASSTER_DATA_REQUEST_SUCCESS"